import { sha256 } from "viem";

const escape = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);

// Self-contained, printable output. Evidence is text, never executable HTML.
// The digest refers to the exact embedded audit JSON, not this HTML wrapper.
export function readableAudit(audit) {
  const text = JSON.stringify(audit, null, 2);
  const digest = sha256(new TextEncoder().encode(text)).slice(2);
  const record = audit.case;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>ProofGuard Change · ${escape(record.id)}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f3f3eb;color:#273024;font:16px/1.7 Arial,sans-serif}main{max-width:920px;margin:40px auto;padding:42px;background:#fffef9;border:1px solid #cdd4c2}header{border-bottom:2px solid #3b522e;padding-bottom:22px}h1{font:36px/1.2 Georgia,serif;margin:15px 0}h2{font:25px Georgia,serif;margin:35px 0 15px}h3{font-size:17px}p{margin:8px 0;color:#4e5b45}small{font-size:12px;color:#66725a}.label{font:12px monospace;letter-spacing:.12em}code,pre{font:12px/1.6 monospace;overflow-wrap:anywhere;white-space:pre-wrap}blockquote{margin:14px 0;padding:14px 18px;border-left:3px solid #a4b88c;background:#f1f3e9}.entry{padding:18px 0;border-bottom:1px solid #d9dece}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:12px 8px;text-align:left;border-bottom:1px solid #d9dece;vertical-align:top;overflow-wrap:anywhere}th{background:#eef1e5}.digest{background:#e8eddd;padding:16px;overflow-wrap:anywhere}details{margin-top:24px}summary{cursor:pointer}footer{margin-top:30px;font-size:12px;border-top:1px solid #ccd3c0;padding-top:20px}@media(max-width:600px){main{padding:22px;margin:0}h1{font-size:28px}table{font-size:11px}}@media print{body,main{background:white}main{max-width:none;margin:0;border:0;padding:0}details{display:none}h2,h3{break-after:avoid}.entry,blockquote{break-inside:avoid}}
  </style></head><body><main><header><span class="label">PROOFGUARD / CHANGE — AUDIT RECORD</span><h1>${escape(record.title)}</h1><p>${escape(record.id)} · source v${escape(record.revision)} · ${escape(audit.network)}</p><small>Observed ${escape(audit.observedAt)} from ${escape(audit.readState)}. This is an independently checkable snapshot, not a cryptographic chain proof.</small></header>
  <h2>The record at a glance</h2><p>${record.sources.length} source revisions · ${record.reviews.length} reviews · ${record.actions.filter(action => action.release).length} jobs queued.</p><p>${escape(audit.executionScope)}</p>
  <p>Contract: <code>${escape(audit.contract)}</code><br>Contract source SHA-256: <code>${escape(audit.contractSourceSha256)}</code></p>
  <h2>1. Evidence and revisions</h2>${record.sources.map(source => `<section class="entry"><h3>Source v${escape(source.revision)}</h3><blockquote>${escape(source.text)}</blockquote><code>SHA-256: ${escape(source.sha256)}</code></section>`).join("")}
  <h2>2. Registered jobs</h2>${record.actions.map(action => `<section class="entry"><h3>${escape(action.label)}</h3><p>${escape(action.condition)}</p><pre>${escape(action.intent_json)}</pre><code>Intent SHA-256: ${escape(action.intent_hash)}</code>${action.release ? `<p>Queue record: <code>${escape(action.release.id)}</code> · source v${escape(action.release.revision)} · ${escape(action.release.effect)}. External execution: ${escape(action.release.external_execution)}.</p>` : "<p>No queue release recorded.</p>"}</section>`).join("")}
  <h2>3. GenLayer decisions</h2>${record.reviews.map(review => `<section class="entry"><h3>Source v${escape(review.revision)} · ${escape(review.policy)}</h3>${review.actions.map(row => `<h3>${escape(row.id)} · ${escape(row.verdict)}</h3><p>${escape(row.reason)}</p><small>Original evidence quote</small><blockquote>${escape(row.old_quote)}</blockquote><small>Revised evidence quote</small><blockquote>${escape(row.new_quote)}</blockquote>`).join("")}</section>`).join("")}
  <h2>4. Permission checks</h2><table><thead><tr><th>Check / job</th><th>Requested / current revision</th><th>Result</th></tr></thead><tbody>${record.attempts.map(attempt => `<tr><td>#${escape(attempt.index)} · ${escape(attempt.action_id)}</td><td>v${escape(attempt.requested_revision)} / v${escape(attempt.current_revision)}</td><td>${escape(attempt.code)}<br>Allowed: ${escape(attempt.allowed)}</td></tr>`).join("")}</tbody></table>
  <h2>5. Verify this record</h2><ol>${audit.verification.map(instruction => `<li>${escape(instruction)}</li>`).join("")}</ol><div class="digest"><strong>Embedded audit JSON SHA-256</strong><br><code>${digest}</code><p>This digest identifies the JSON below. A separately downloaded or later archived snapshot can differ because its observation time or chain state changed.</p></div><details><summary>Complete machine-readable audit JSON</summary><pre id="audit-json">${escape(text)}</pre></details><footer>Decision authority: GenLayer. Report prepared by ProofGuard Change. Downloading this file does not publish it to Arweave. Permanent publication is a separate, explicit action.</footer></main></body></html>`;
}
