"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, CheckCheck, Download, FileInput, LoaderCircle, LockKeyhole, RefreshCw, ShieldCheck, Terminal, Wallet } from "lucide-react";
import { ProjectBrand } from "./change-home";
import { DownloadLink } from "./download-link";
import { NetworkActivity } from "./change-network-activity";
import { assessAgentRequest, MAX_REQUEST_BYTES, parseAgentRequest, requestRegistration } from "@/genlayer/agent-request.mjs";
import { browserSha256, createBrowserInspector, type EvidenceSnapshot } from "@/genlayer/evidence-desk-client";
import { connectNetworkWallet, resumeNetworkTransaction, writeNetwork, type NetworkProgress } from "@/genlayer/change-network-client";
import { readNetworkPending, rememberNetworkPending } from "@/genlayer/change-network-session.mjs";
import { observeWallet } from "@/genlayer/wallet-connection";
import { walletErrorMessage } from "@/genlayer/wallet-network.mjs";
import { PROOFGUARD_REPOSITORY } from "@/config/evidence-desk";

type Envelope = Awaited<ReturnType<typeof parseAgentRequest>>;
const help: Record<string, string> = {
  INVALID_AGENT_REQUEST: "Use a ProofGuard request JSON generated by the MCP connector. Unknown fields and unsupported tools are rejected.",
  REQUEST_DIGEST_MISMATCH: "The request changed after it was prepared. Ask the agent for a new request.",
  STALE_SOURCE_REVISION: "This request refers to an older source. Ask the agent to inspect the current evidence and prepare a new request.",
  SOURCE_OWNER_APPROVAL_REQUIRED: "The proposed owner is not approved for this source. The source publisher must approve that wallet first.",
  SOURCE_WORKFLOW_LIMIT: "This source already has four workflows. The contract cannot register another one.",
  WORKFLOW_REQUEST_CONFLICT: "This workflow ID is already registered with different details. Ask the agent for a different ID.",
  REQUEST_WORKSPACE_MISMATCH: "The network record does not match this request’s source or contract code.",
  RPC_READ_FAILED: "The network could not be read. Retry the check; no approval has been established.",
  READ_TIMEOUT: "The network did not respond in time. Retry the check.",
};

export function AgentRequests() {
  const [raw, setRaw] = useState("");
  const [envelope, setEnvelope] = useState<Envelope | null>(null);
  const [snapshot, setSnapshot] = useState<EvidenceSnapshot | null>(null);
  const [state, setState] = useState("");
  const [account, setAccount] = useState("");
  const [consent, setConsent] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [phase, setPhase] = useState("");
  const [progress, setProgress] = useState<NetworkProgress | null>(null);
  const [pending, setPending] = useState<NetworkProgress | null>(() => readNetworkPending(localStorage));
  const [dismissed, setDismissed] = useState(false);
  const lock = useRef(false);
  const r = envelope?.request;

  useEffect(() => {
    const fragment = window.location.hash;
    if (!fragment.startsWith("#request=")) return;
    window.history.replaceState(null, "", window.location.pathname + window.location.search);
    try {
      const encoded = fragment.slice(9);
      if (encoded.length > MAX_REQUEST_BYTES * 1.4 || !/^[A-Za-z0-9_-]+$/.test(encoded)) throw Error();
      const decoded = new TextDecoder("utf-8", { fatal: true }).decode(Uint8Array.from(atob(encoded.replace(/-/g, "+").replace(/_/g, "/")), c => c.charCodeAt(0)));
      setRaw(decoded);
    } catch { setError("This request link could not be opened. Import the original JSON file instead."); }
  }, []);
  useEffect(() => observeWallet(() => { setAccount(""); setConsent(false); }), []);
  useEffect(() => {
    if (!busy) return;
    const prevent = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; };
    window.addEventListener("beforeunload", prevent);
    return () => window.removeEventListener("beforeunload", prevent);
  }, [busy]);

  async function run(action: () => Promise<void>) {
    if (lock.current) return;
    lock.current = true; setBusy(true); setError(""); setNotice(""); setDismissed(false);
    try { await action(); }
    catch (problem) {
      const code = problem instanceof Error ? problem.message : "";
      setError(help[code] || (/^[A-Z_]+$/.test(code) ? `Verification stopped: ${code}. No new permission was established.` : walletErrorMessage(code || "The operation could not be completed.")));
    } finally { lock.current = false; setBusy(false); }
  }
  async function verify(value: Envelope) {
    const request = value.request;
    const inspector = await createBrowserInspector({ network: "studionet", contract: request.contract, sourceId: request.sourceId }, setPhase);
    const fresh = await inspector.inspectSource() as EvidenceSnapshot;
    const next = assessAgentRequest(value, fresh);
    setSnapshot(fresh); setState(next); return next;
  }
  async function checkRequest() {
    setSnapshot(null); setState(""); setConsent(false); setEnvelope(null);
    const checked = await parseAgentRequest(raw, browserSha256);
    setEnvelope(checked); await verify(checked);
  }
  function edit(value: string) {
    setRaw(value); setEnvelope(null); setSnapshot(null); setState(""); setConsent(false); setError(""); setNotice(""); setProgress(null);
  }
  function onProgress(value: NetworkProgress) {
    setProgress(value); rememberNetworkPending(localStorage, value);
    if (value.hash) setPending(value.finalized || value.failed ? null : value);
  }
  async function register() {
    if (!envelope || !consent || pending) return;
    // Re-read immediately before requesting a signature; the contract checks the
    // exact expected revision again when registration executes.
    setSnapshot(null); setState("");
    if (await verify(envelope) !== "AWAITING_OWNER_REGISTRATION") return;
    await writeNetwork(envelope.request.contract, "register_workflow", requestRegistration(envelope), onProgress, { expectedAccount: envelope.request.workflow.owner });
    await verify(envelope); setConsent(false);
    setNotice("Workflow registered. Review the evidence and authorize supported jobs in the Live workspace.");
  }
  async function recover() {
    if (!pending?.hash) return;
    const previous = pending;
    await resumeNetworkTransaction(pending.hash, value => onProgress({ ...previous, ...value }));
    if (envelope) { setSnapshot(null); setState(""); await verify(envelope); }
    setNotice("The existing transaction was checked. No duplicate was sent.");
  }
  const workspace = r ? `./?mode=live&contract=${r.contract}&source=${encodeURIComponent(r.sourceId)}` : "./?mode=live";
  const registered = state === "REGISTERED";

  return <div className="pg-site ed-app ar-app">
    <a href="#requests-main" className="pg-skip">Skip to request</a>
    <header className="ed-header"><ProjectBrand /><nav aria-label="Application navigation"><a href="./?mode=inspect">Evidence Desk</a><a href="./?mode=request" aria-current="page">Agent requests</a><a href="./?mode=live">Live workspace <ArrowUpRight size={14} /></a></nav></header>
    <main className="ed-main" id="requests-main">
      <div className="ed-intro"><div><span className="ed-eyebrow">AGENT → OWNER → EXECUTOR</span><h1>Your agent proposes.<br />You keep control.</h1><p>Review an exact job request against current evidence, then register it with your wallet.</p></div><span className="ed-no-wallet"><ShieldCheck size={17} />No signature on import</span></div>
      <div className="ar-layout">
        <section className="ed-panel ar-import"><span className="ed-eyebrow">01 / IMPORT A REQUEST</span><h2>From your agent, to you.</h2><p>Ask your connected agent to use <code>proofguard_prepare_workflow</code>. Paste its request JSON or open the file it returns.</p>
          <label className="ar-file"><FileInput size={17} />Choose request JSON<input type="file" accept=".json,application/json" disabled={busy || !!pending} onChange={e => { const file = e.target.files?.[0]; if (!file) return; void run(async () => { if (file.size > MAX_REQUEST_BYTES) throw Error("INVALID_AGENT_REQUEST"); edit(await file.text()); }); e.target.value = ""; }} /></label>
          <label className="ar-json">Request JSON<textarea rows={5} value={raw} maxLength={MAX_REQUEST_BYTES} spellCheck={false} disabled={busy || !!pending} onChange={e => edit(e.target.value)} placeholder={'{"request": {…}, "sha256": "…"}'} /></label>
          <button className="ed-button ed-dark" disabled={busy || !raw.trim()} onClick={() => void run(checkRequest)}>{busy && !progress ? <LoaderCircle className="ed-spin" size={17} /> : <ShieldCheck size={17} />}Check request & source</button>
          <details className="ar-guide"><summary>What happens after import?</summary><ol><li>Check the current source and every requested job.</li><li>The named owner registers the workflow.</li><li>GenLayer reviews it. The owner separately permits supported jobs.</li><li>The registered executor can create the approved contract artifact.</li></ol><p>A request checksum identifies its contents. It does not prove who sent it. Imported text is evidence to inspect, never an instruction to your wallet.</p><a href={`${PROOFGUARD_REPOSITORY}/blob/feature/evidence-desk/docs/AGENT_REQUESTS.md`} target="_blank" rel="noreferrer">Agent integration guide <ArrowUpRight size={13} /></a></details>
        </section>
        <section className="ar-review" aria-label="Request review">
          {busy && !progress && <div className="ed-verification ed-working ar-reading" role="status"><LoaderCircle className="ed-spin" size={18} /><span>{phase || "Checking the request…"}</span></div>}
          {error && <div className="ed-error" role="alert"><LockKeyhole size={22} /><div><h2>Check stopped</h2><p>{error}</p></div></div>}
          {!envelope && !error && <div className="ar-empty"><Terminal size={36} /><h2>An exact request, not a blank cheque.</h2><p>Source revision, job conditions, tool parameters and executor stay together. You decide whether to register them.</p><div><span>Source pinned</span><span>Owner checked</span><span>Jobs bounded</span></div></div>}
          {envelope && r && <>
            <section className="ed-panel ar-request-card"><div className="ar-card-heading"><div><span className="ed-eyebrow">02 / REVIEW THE DETAILS</span><h2>{r.workflow.title}</h2><code>{r.workflow.id}</code></div>{snapshot && <span className="ar-state"><CheckCheck size={15} />{registered ? "Registered" : "Ready to register"}</span>}</div>
              <div className="ar-source-pin"><ShieldCheck size={20} /><div><strong>{r.sourceId} · v{r.sourceRevision}</strong><small>{snapshot ? `Verified ${new Date(snapshot.observedAt).toLocaleTimeString()} · Studionet` : "Current source has not been verified"}</small></div><button className="ed-button" disabled={busy} aria-label="Refresh request status" onClick={() => void run(checkRequest)}><RefreshCw size={15} /></button></div>
              <div className="ar-accounts"><div><span>OWNER · REGISTERS & AUTHORIZES</span><code>{r.workflow.owner}</code></div><div><span>EXECUTOR · CREATES OUTPUT</span><code>{r.workflow.executor}</code></div></div>
              {r.workflow.jobs.map((job: { id: string; label: string; condition: string; tool: string; target: string; payload: { currency: string; unit_price: number; quantity?: number; shipping?: string } }, index: number) => <article className="ar-job" key={job.id}><div><span>0{index + 1}</span><h3>{job.label}</h3></div><p>{job.condition}</p><dl><div><dt>Tool</dt><dd>{job.tool === "prepare_price_report" ? "Price report" : "Purchase-order draft"}</dd></div><div><dt>Target</dt><dd>{job.target}</dd></div><div><dt>Parameters</dt><dd>{job.payload.currency} {job.payload.unit_price} / unit{job.payload.quantity ? ` · quantity ${job.payload.quantity} · ${job.payload.shipping} shipping` : ""}</dd></div></dl></article>)}
              <details className="ar-guide"><summary>Source evidence & exact bindings</summary>{snapshot && <p className="ar-evidence">{snapshot.bundle.source.versions.at(-1)?.text}</p>}<p>Contract <code>{r.contract}</code></p><p>Source SHA-256 <code>{r.sourceSha256}</code></p><p>Request SHA-256 <code>{envelope.sha256}</code></p><DownloadLink className="ed-button" name={`${r.workflow.id}.proofguard.json`} text={JSON.stringify(envelope, null, 2)}><Download size={14} />Save request</DownloadLink></details>
            </section>
            {snapshot && <section className="ar-approval"><div><span className="ed-eyebrow">03 / {registered ? "CONTINUE IN LIVE" : "OWNER DECISION"}</span><h3>{registered ? "Registration is complete." : "Register these exact jobs?"}</h3><p>{registered ? "Continue to evidence review and per-job authorization. Registration alone grants no execution permit." : "This records the workflow publicly on GenLayer. Review and execution permission are separate steps."}</p></div>
              {registered ? <a href={workspace} className="ed-button ed-dark">Review & authorize in Live <ArrowRight size={16} /></a> : <>
                <button className="ed-button" disabled={busy || !!pending} onClick={() => void run(async () => { setPhase("Connect the owner wallet in MetaMask."); const value = await connectNetworkWallet(); setAccount(value.account); setConsent(false); })}><Wallet size={16} />{account ? "Change / reconnect wallet" : "Connect owner wallet"}</button>
                {account && account !== r.workflow.owner && <p role="alert" className="ar-wrong-owner">The connected account is not this request’s owner. Select {r.workflow.owner} in your wallet.</p>}
                {account === r.workflow.owner && <><label className="ar-consent"><input type="checkbox" checked={consent} disabled={busy || !!pending} onChange={e => setConsent(e.target.checked)} />I reviewed the conditions, parameters and executor above.</label><button className="ed-button ed-dark" disabled={busy || !!pending || !consent} onClick={() => void run(register)}>{busy ? <LoaderCircle size={17} className="ed-spin" /> : <CheckCheck size={17} />}Register with my wallet</button></>}
              </>}
            </section>}
          </>}
          {pending && <p className="ar-pending">A submitted transaction needs a status check before another write. <button onClick={() => void run(recover)} disabled={busy}>Check transaction</button></p>}
        </section>
      </div>
      <footer className="ed-trust"><LockKeyhole size={17} /><p>Protected tools create contract reports and drafts. They do not place orders, send payments or execute instructions found in source text.</p><a href="./?mode=inspect">Inspect a record <ArrowUpRight size={14} /></a></footer>
    </main>
    {(progress || pending) && <NetworkActivity progress={progress || pending} pending={pending} busy={busy} error={error} notice={notice} operation={phase} dismissed={dismissed} onDismiss={() => setDismissed(true)} onRecover={() => void run(recover)} />}
  </div>;
}
