"use client";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Copy, Download, Terminal } from "lucide-react";
import { PROOFGUARD_REPOSITORY, type EvidenceConnection } from "@/config/evidence-desk";
import type { EvidenceSnapshot } from "@/genlayer/evidence-desk-client";
import { agentConfiguration, agentCheckCommand, firstAgentPrompt } from "@/genlayer/agent-setup.mjs";
import { DownloadLink } from "./download-link";

const install = "git clone --branch feature/evidence-desk https://github.com/Vevivo/proofguard-change.git\ncd proofguard-change\nnpm ci";
export function AgentSetup({ connection, snapshot, copy }: { connection: EvidenceConnection; snapshot: EvidenceSnapshot; copy: (text: string, label: string) => Promise<void> }) {
  const [step, setStep] = useState(0);
  const [path, setPath] = useState("");
  const config = agentConfiguration(path, connection);
  const configText = config ? JSON.stringify(config, null, 2) : "";
  const checkCommand = agentCheckCommand(connection);
  const prompt = firstAgentPrompt(snapshot);
  return <section className="ed-panel ed-agent-setup" aria-label="Agent setup">
    <div className="ed-setup-heading"><div><span className="ed-eyebrow">AGENT SETUP · LOCAL MCP</span><h3>One source. Ready for your agent.</h3><p className="ed-muted">Use a desktop or developer client that supports local MCP servers. Your wallet stays in Live.</p></div><span className="ed-setup-source">{connection.sourceId} · v{snapshot.source.revision}</span></div>
    <nav className="ed-setup-steps" aria-label="Agent setup steps">{["Install & check", "Add to your client", "Run your first task"].map((label, index) => <button key={label} aria-current={step === index ? "step" : undefined} onClick={() => setStep(index)}><span>0{index + 1}</span>{label}</button>)}</nav>
    <div className="ed-setup-body" key={step}>
      {step === 0 && <><h4>Check the connector before opening your agent.</h4><p>Install Node.js 22.13 or later and Git, then run these commands in a terminal. Already have this checkout? Update it and run <code>npm ci</code>.</p><div className="ed-code-head"><span>Install once</span><button onClick={() => void copy(install, "Install commands")}><Copy size={14} />Copy commands</button></div><pre>{install}</pre><div className="ed-code-head"><span>Check this exact workspace</span><button onClick={() => void copy(checkCommand, "Connection check")}><Copy size={14} />Copy check</button></div><pre>{checkCommand}</pre><p className="ed-setup-note">The check starts the actual MCP server and reads this source. Look for <strong>MCP connection verified</strong>. If it fails, it prints the failed step and what to check. It sends no transaction.</p><button className="ed-button ed-dark" onClick={() => setStep(1)}>Next: client configuration <ArrowRight size={15} /></button></>}
      {step === 1 && <><h4>Add the server in your MCP client.</h4><p>Enter the full folder path to your checkout. This creates a configuration for the selected source, with read access and unsigned requests only.</p><label className="ed-path">ProofGuard folder on your computer<input value={path} onChange={e => setPath(e.target.value)} placeholder="C:/projects/proofguard-change or /Users/you/proofguard-change" spellCheck={false} autoComplete="off" /></label>{!config && <p className="ed-setup-note">Use an absolute folder path. Example: <code>C:/projects/proofguard-change</code>. The file <code>agents/mcp-server.mjs</code> must exist inside it.</p>}{config && <><div className="ed-code-head"><span>Merge into your client’s MCP configuration</span><button onClick={() => void copy(configText, "MCP configuration")}><Copy size={14} />Copy configuration</button></div><pre>{configText}</pre><div className="ed-setup-actions"><DownloadLink className="ed-button" name="proofguard-mcp-config.json" text={configText}><Download size={14} />Save configuration</DownloadLink><button className="ed-button ed-dark" onClick={() => setStep(2)}>Next: first agent task <ArrowRight size={15} /></button></div></>}<details className="ed-detail"><summary>Where does this configuration go?</summary><p>Use the local MCP server settings in your agent app. Some clients accept the whole <code>mcpServers</code> object; others ask for the <code>command</code> and <code>args</code> separately. Merge the ProofGuard entry without removing your other servers, then enable or restart it. A web-only client that requires a remote HTTPS URL cannot use this local configuration.</p></details></>}
      {step === 2 && <><h4>Ask your agent to explain this record.</h4><p>Paste this task into the client where you added ProofGuard. It asks for fresh evidence and existing outputs, without authorizing work.</p><pre className="ed-agent-prompt">{prompt}</pre><div className="ed-setup-actions"><button className="ed-button ed-dark" onClick={() => void copy(prompt, "First agent task")}><Copy size={15} />Copy first task</button><a className="ed-button" href="./?mode=request">Review an agent request <ArrowRight size={15} /></a></div><p className="ed-setup-note"><strong>What success looks like:</strong> the agent calls ProofGuard tools and returns this source ID, its current revision and the job decisions. This website cannot see your client connection; a copied configuration alone does not verify it.</p>{connection.network === "studionet" && <details className="ed-detail"><summary>Then prepare your own work</summary><p>Connect to a source where your wallet is an approved owner. Ask the agent to use <code>proofguard_prepare_workflow</code> with your owner and executor addresses, job conditions, tool and parameters. Open its review link or import its request file here. Registration and each execution permit still require approval.</p></details>}</>}
    </div>
    <div className="ed-setup-footer"><Terminal size={15} /><span>Local connection · no signing key needed</span><a href={`${PROOFGUARD_REPOSITORY}/blob/feature/evidence-desk/docs/AGENT_CONNECTOR.md`} target="_blank" rel="noreferrer">Connection guide <ArrowUpRight size={14} /></a><a href={`${PROOFGUARD_REPOSITORY}/blob/feature/evidence-desk/docs/SERVER_RUNTIME.md`} target="_blank" rel="noreferrer">Existing server setup <ArrowUpRight size={14} /></a></div>
  </section>;
}
