"use client";

import { Fragment, useState, type CSSProperties } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, FileCheck2, FileText, Fingerprint, GitBranch, History, LockKeyhole, Pause, Play, ShieldCheck, Terminal, Code2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useReferenceMotion } from "./use-reference-motion";

export function ProjectBrand() {
  return <a className="pg-brand" href="./" aria-label="ProofGuard Change home"><ShieldCheck size={25} /><span>ProofGuard<span className="pg-brand-divider">/</span><b>Change</b></span></a>;
}

const nodes = [
  { id: "source", label: "Source", detail: "A publisher correction creates a new evidence revision. Unused permissions for the old revision are fenced.", color: "black", Icon: FileText, x: 300, y: 40, size: "pill" },
  { id: "supply", label: "Supply workflow", detail: "The procurement workflow contains an urgent event order and a stock order, each with its own delivery condition.", color: "mint", Icon: GitBranch, x: 165, y: 170, size: "main" },
  { id: "market", label: "Market workflow", detail: "A separate workflow checks the quoted unit price. It shares the source, while retaining its own owner and job intent.", color: "yellow", Icon: History, x: 435, y: 170, size: "main" },
  { id: "intent", label: "Exact intent", detail: "The permission binds the specific tool, target and parameters. A different action cannot reuse it.", color: "purple", Icon: Fingerprint, x: 72, y: 310, size: "side" },
  { id: "guard", label: "ProofGuard", detail: "GenLayer’s intelligent contract checks each condition. At execution, the contract checks the current revision and exact intent again.", color: "black", Icon: ShieldCheck, x: 300, y: 310, size: "big" },
  { id: "revision", label: "Revision check", detail: "A previously granted permission cannot bypass a source correction. Execution must match the current source revision.", color: "mint", Icon: History, x: 528, y: 310, size: "side" },
  { id: "held", label: "Event · held", detail: "The revised source says dispatch on 10 September, not guaranteed arrival. The event order is held and creates no output.", color: "yellow", Icon: LockKeyhole, x: 125, y: 467, size: "outcome" },
  { id: "stock", label: "Stock · ready", detail: "The standard-delivery deadline is still supported. With a fresh permission, this job can produce a purchase-order draft.", color: "mint", Icon: FileCheck2, x: 300, y: 467, size: "outcome" },
  { id: "price", label: "Price · ready", detail: "The unit price remains EUR 240. With a fresh permission, this job can produce its price report.", color: "purple", Icon: FileCheck2, x: 475, y: 467, size: "outcome" },
  { id: "audit", label: "Audit record", detail: "Source history, review reasons, permissions and outputs can be inspected together and exported as a readable record.", color: "black", Icon: Fingerprint, x: 300, y: 615, size: "audit" },
];
const paths = [
  "M300 70C300 102 210 107 165 130", "M300 70C300 102 390 107 435 130",
  "M165 215C165 249 230 255 270 285", "M435 215C435 249 370 255 330 285",
  "M115 310H240", "M485 310H360", "M300 370C300 413 125 405 125 426", "M300 370V426", "M300 370C300 413 475 405 475 426",
  "M125 510C125 561 268 548 300 594", "M300 510V594", "M475 510C475 561 332 548 300 594",
];
function Words({ text }: { text: string }) {
  return <>{text.split(" ").map((word, i) => <Fragment key={i}><span className="rf-word"><span>{word}</span></span>{" "}</Fragment>)}</>;
}

export function ChangeHome() {
  const [motion, setMotion] = useState(true);
  const [selected, setSelected] = useState("guard");
  const root = useReferenceMotion(motion);
  const current = nodes.find(n => n.id === selected)!;
  return <div className="pg-site pg-reference" ref={root} data-motion={motion ? "on" : "off"}>
    <div className="rf-cursor" aria-hidden="true" />
    <a href="#project" className="pg-skip">Skip to project</a>
    <header className="rf-header"><ProjectBrand /><nav aria-label="Project navigation"><a href="#mechanism">How it works</a><a href="./?mode=inspect">Evidence Desk</a><a href="./?mode=request">Agent requests</a></nav><Button asChild variant="outline" className="rf-header-button"><a href="./?mode=live">Open workspace <ArrowUpRight size={16} /></a></Button></header>
    <main id="project">
      <section className="rf-hero">
        <div className="rf-hero-copy"><div className="rf-eyebrow">BUILT FOR GENLAYER INTELLIGENT CONTRACTS</div><h1>{["Evidence changes.", "Good agents", "adapt."].map(line => <span className="rf-title-line" key={line}><span className="rf-title-inner">{line}</span></span>)}</h1><p className="rf-hero-desc">One corrected source can change what an agent should do. ProofGuard binds permission to the evidence behind it. Inspect real decisions, hold affected jobs, and give your agent a record it can check.</p><div className="rf-hero-actions"><Button asChild className="rf-button rf-button-black rf-hero-cta"><a href="./?mode=inspect&reference=correction">Inspect a real record <span className="rf-arrow"><ArrowRight size={17} /></span></a></Button><a href="./?mode=demo"><Play size={15} />Watch the 45-second demo</a></div><a className="rf-under-link" href="#mechanism">A closer look at the mechanism <ArrowDown size={15} /></a></div>
        <div className="rf-hero-right"><div className="rf-constellation" aria-label="Interactive illustration of ProofGuard dependencies"><div className="rf-constellation-inner"><svg className="rf-constellation-lines" viewBox="0 0 600 660" fill="none" aria-hidden="true">{paths.map(d => <path d={d} key={d} />)}</svg>{nodes.map(({ id, label, color, Icon, x, y, size }, i) => <button className={`rf-tile rf-tile-${size} rf-${color}`} style={{ left: `${x / 6}%`, top: `${y / 6.6}%`, "--float-delay": `${i * -.4}s`, "--float-duration": `${4.2 + i * .2}s` } as CSSProperties} key={id} onClick={() => setSelected(id)} aria-pressed={selected === id} aria-describedby="constellation-detail"><span className="rf-tile-float"><span className="rf-tile-inner"><Icon strokeWidth={1.55} /><span>{label}</span></span></span></button>)}</div></div><div className="rf-map-caption"><span>ILLUSTRATIVE FLOW · SELECT A PIECE</span><button className="rf-motion-toggle" onClick={() => setMotion(!motion)} aria-pressed={!motion} aria-label={motion ? "Pause page animations" : "Enable page animations"}>{motion ? <Pause size={14} /> : <Play size={14} />}<span>{motion ? "Pause motion" : "Enable motion"}</span></button></div><div className="rf-map-detail" id="constellation-detail" role="status"><strong>{current.label}</strong><p>{current.detail}</p></div></div>
      </section>
      <section className="rf-workspace-strip" aria-label="Workspace capabilities"><h2>From evidence<br />to execution.</h2><div className="rf-pills"><a href="#bind" className="rf-pill rf-mint"><Fingerprint size={23} /><span>Exact intent</span></a><a href="#review" className="rf-pill rf-yellow"><GitBranch size={23} /><span>Selective review</span></a><a href="#protect" className="rf-pill rf-purple"><ShieldCheck size={23} /><span>Protected output</span></a></div><a href="#mechanism" className="rf-learn">Discover the mechanism <ArrowDown size={15} /></a></section>
      <section className="rf-facts" aria-label="Guided scenario structure"><div className="rf-facts-label">INSIDE THE GUIDED SCENARIO</div><div className="rf-stats-grid">{[{n:1,label:"Shared evidence source"},{n:2,label:"Independent workflows"},{n:3,label:"Individually checked jobs"},{n:2,label:"Eligible outputs after correction"}].map(({n,label}) => <div className="rf-stat" key={label}><span className="rf-stat-number" aria-hidden="true" data-num={n}>{String(n).padStart(2,"0")}</span><span className="nw-sr">{n}</span><span>{label}</span></div>)}</div></section>
      <section className="rf-proof-entry" id="evidence-desk"><div><div className="rf-eyebrow">NEW / A WORKING SURFACE FOR PEOPLE & AGENTS</div><h2>The decision is only useful<br />if you can inspect it.</h2><p>Open a finalized record without a wallet. Follow a source correction through the jobs it affects, inspect the generated artifact, then connect an MCP client to the same evidence. Your agent can prepare exact job requests for you to review and register.</p><div className="rf-proof-links"><Button asChild className="rf-button rf-button-black"><a href="./?mode=inspect&reference=correction">Open Evidence Desk <ArrowRight size={16} /></a></Button><a href="https://github.com/Vevivo/proofguard-change" target="_blank" rel="noreferrer"><Code2 size={17} />Explore the code</a></div></div><div className="rf-proof-terminal"><span>READ ONLY / LIVE TEST RECORD <Terminal size={18} /></span><strong>source: CORRECTION-REGRESSION-01</strong><p>A controlled test with separate owner and executor accounts. Every inspection reads the network again; sample data never replaces an unavailable result.</p><div className="rf-proof-checks"><span><Fingerprint size={14} />Code & content checks</span><span><GitBranch size={14} />Per-job decisions</span><span><FileCheck2 size={14} />Bound outputs</span></div></div></section>
      <section className="rf-features" id="mechanism"><div className="rf-section-head"><div><div className="rf-eyebrow">01 / HOW PROOFGUARD WORKS</div><h2 className="rf-reveal-title"><Words text="One source. Different jobs. Independent decisions." /></h2></div><p>Each job carries its own condition, owner and exact action. A shared source connects the work.</p></div><div className="rf-feature-cards">{[{id:"bind",color:"mint",num:"01",verb:"Bind",title:"Make the intent explicit.",copy:"Record the tool, target, parameters and condition. A permission belongs to that exact job and evidence revision.",Icon:Fingerprint},{id:"review",color:"yellow",num:"02",verb:"Review",title:"Check what actually changed.",copy:"A publisher correction fences unused permissions. GenLayer evaluates whether each job’s condition is still supported.",Icon:GitBranch},{id:"protect",color:"purple",num:"03",verb:"Protect",title:"Continue with a reason.",copy:"Supported jobs can earn fresh permissions. Execution checks the current revision again, then records the protected output.",Icon:ShieldCheck}].map(({id,color,num,verb,title,copy,Icon}) => <article className="rf-feature-wrap" id={id} key={id}><div className={`rf-feature-card rf-${color}`}><div className="rf-card-num">{num} / {verb.toUpperCase()}</div><h3>{title}</h3><p>{copy}</p><span className="rf-card-icon"><Icon size={29} strokeWidth={1.6} /></span></div></article>)}</div></section>
      <section className="rf-consequences" id="consequences"><div className="rf-eyebrow">02 / A SMALL EDIT. A DIFFERENT CONSEQUENCE.</div><div className="rf-change-words"><span>“Delivery”</span><ArrowRight size={35} /><strong>“Dispatch”</strong></div><h2 className="rf-reveal-title"><Words text="The promise changed. Only the affected job should stop." /></h2><p className="rf-consequence-desc">Express dispatch on 10 September no longer guarantees arrival for the event. The standard-delivery deadline and quoted price can still hold.</p><div className="rf-result-strip"><div className="rf-result held"><LockKeyhole size={20} /><span>Event order</span><b>Held</b></div><div className="rf-result ready"><Check size={20} /><span>Stock order</span><b>Can proceed</b></div><div className="rf-result ready"><Check size={20} /><span>Price report</span><b>Can proceed</b></div></div><p className="rf-scope">Protected tools create purchase-order drafts and price reports. They do not submit supplier orders or transfer funds.</p></section>
      <section className="rf-final-cta" id="enter"><div className="rf-final-card"><div className="rf-eyebrow">03 / YOUR NEXT MOVE</div><h2 className="rf-reveal-title"><Words text="Let the right jobs" /><br /><span className="rf-accent"><Words text="keep moving." /></span></h2><p>Follow one complete decision, from the original evidence to the final record. Then bring your own source and workflow.</p><div className="rf-entry-options"><div><Button asChild className="rf-button rf-button-yellow"><a href="./?mode=demo">Demo <span className="rf-arrow"><Play size={17} /></span></a></Button><small>~45 seconds · sample data · no wallet</small></div><div><Button asChild variant="outline" className="rf-button rf-button-outline"><a href="./?mode=live">Live <span className="rf-arrow"><ArrowUpRight size={18} /></span></a></Button><small>Your wallet · GenLayer test network</small></div></div><span className="rf-live-note">Inspect existing evidence without a wallet. Connect a wallet when you want to create or authorize work.</span></div></section>
    </main>
    <footer className="rf-footer"><div><ProjectBrand /><p>Evidence changes. Permission adapts.</p></div><nav aria-label="Footer navigation"><a href="./?mode=inspect">Evidence Desk</a><a href="https://github.com/Vevivo/proofguard-change" target="_blank" rel="noreferrer">GitHub</a><a href="./?mode=request">Agent requests</a><a href="./?mode=demo">Explore Demo</a><a href="./?mode=live">Open Live</a><a href="https://genlayer.com" target="_blank" rel="noreferrer">GenLayer <ArrowUpRight size={14} /></a></nav><div className="rf-footer-bottom"><span>ProofGuard Change</span><span>Shared evidence. Independent decisions.</span></div></footer>
  </div>;
}
